### ISSUE TITLE
First thoughts

### ISSUE THREAD

**Issue by agrzegorczyk-leonsoftware** [FrederikP/sshaws#1]
https://github.com/FrederikP/sshaws/blob/c65872e44e0e11ba5a038eb1fb8eb03c935097b1/sshaws#L25
This assumes that you have set default region (e.g. in ~/.aws/config file or as AWS_DEFAULT_REGION env variable) or crashes otherwise.
Safer way to get default region (if available) is:
`boto3.session.Session().region_name`

https://github.com/FrederikP/sshaws/blob/c65872e44e0e11ba5a038eb1fb8eb03c935097b1/sshaws#L63
Some debugging residue ?

https://github.com/FrederikP/sshaws/blob/c65872e44e0e11ba5a038eb1fb8eb03c935097b1/sshaws#L91
I suppose this should be:`subprocess.run(command_list)` ?

**Comment by FrederikP** [comment]
Hi!
Thanks a lot. Looks like I was not very awake when I did the last changes yesterday.

I just changed all of it and verified the command works for me. Can you take a look? (version 0.3.2)

Thanks again

**Comment by agrzegorczyk-leonsoftware** [comment]
Now works fine, thank you. :)
Nice script btw, I didn't know about ec2-instance-connect api before.
