### ISSUE TITLE
aliases

### ISSUE THREAD

**Issue by geoffreywiseman** [FrederikP/sshaws#3]
Would be nice if in the `sshaws` config, you could add aliases for instances, so that you could connect to them using something a little more memorable than instance ids. ;)

**Comment by FrederikP** [comment]
Hi,
good idea, thanks.
I'll try to add it with the next version.

**Comment by derekjbernard** [comment]
added a pull request for the aliases feature. #5 
https://github.com/FrederikP/sshaws/pull/5

I also have a feature branch for adding profile support in my fork. I can do a pull for that too if you like.

**Comment by derekjbernard** [comment]
I just wanted to mention. I welcome any critique on my code. I'd love to improve it and / or change it to meet any conventions you'd like to follow in this project.

**Comment by FrederikP** [comment]
Hi @derekjbernard ,
thanks for all the work. I didn't have much time (birth of my son) but I'll take a look now.

**Comment by FrederikP** [comment]
@derekjbernard s PR was merged and is included in version 0.4.0
